version = 1

[[annotations]]
path = ["app/**","cpp/**","js/**","openlayers/**","python/pmtiles/**","serverless/**"]
SPDX-FileCopyrightText = "2021 and later, Protomaps LLC and contributors"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = ["python/rio-pmtiles/**"]
SPDX-FileCopyrightText = "2025 and later, Protomaps LLC and contributors; 2024-2021 Mapbox"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "spec/**/*.md"
SPDX-FileCopyrightText = "2021 and later, Protomaps LLC and contributors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "spec/v3/protomaps(vector)ODbL_firenze.pmtiles"
SPDX-FileCopyrightText = "© OpenStreetMap Contributors"
SPDX-License-Identifier = "ODbL-1.0"

[[annotations]]
path = "stamen_toner(raster)CC-BY+ODbL_z3.pmtiles"
SPDX-FileCopyrightText = "Stamen Design, © OpenStreetMap Contributors"
SPDX-License-Identifier = "CC-BY-4.0"